# Generated by Django 4.2 on 2023-04-13 13:18

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('exercise', '운동'), ('transport', '교통'), ('cleaning', '청소'), ('leisure', '여가생활'), ('digital', '디지털'), ('save', '절약')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='mission',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level1'), (2, 'Level2'), (3, 'Level3'), (4, 'Level4')]),
        ),
    ]
